# Generated by Django 6.0.5 on 2026-05-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistcache',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
